### ISSUE TITLE
Change BasisStructure to BasisMatrix?

### ISSUE THREAD

**Issue by spencerlyon2** [QuantEcon/BasisMatrices.jl#24]
Should we change the name of the `BasisStructure` Type to `BasisMatrix`?

I think this is a bit more clear about what the type actually as AND it has the benefit if matching the name of the package. 

For backwards compatibility we'd have two options:
1. Keep `BasisStructure` around as a deprecated name and encourage people to use `BasisMatrix`
2. After changing the name we could define`typealias BasisStructure BasisMatrix` so that both names always remain valid.

I'd be happy either way.

@albep and @vgregory757 what do you think?

**Comment by albep** [comment]
I'm in favor of the change for the reasons you said. Also, I prefer making `BasisStructure` deprecated and encourage the new type name

**Comment by vgregory757** [comment]
Makes sense to me. I agree with option 1/@albep.

**Comment by spencerlyon2** [comment]
Done
