### ISSUE TITLE
Update README.md?

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/BasisMatrices.jl#35]
It would be helpful if `README.md` is updated, at least for the [description of `Basis` type](https://github.com/QuantEcon/BasisMatrices.jl/blame/master/README.md#L110-L116).
It is now

```jl
type Basis{N,TP<:Tuple}
    params::TP     # params to construct basis
end
```

as defined [here](https://github.com/QuantEcon/BasisMatrices.jl/blob/47a15a135cca71900d5bccdf61445e59772ec24f/src/basis.jl#L17-L19).

**Comment by sglyon** [comment]
Great point, the readme is definitely out of sync with the codebase.

**Comment by vgregory757** [comment]
I really like [this file](https://github.com/QuantEcon/BasisMatrices.jl/blob/master/demo/basis_mat_formats.jl) that @sglyon put together a while ago. It has examples and does a good job of explaining the differences between all the formats.
