### ISSUE TITLE
0.7 compat

### ISSUE THREAD

**Issue by albop** [QuantEcon/BasisMatrices.jl#52]
Anybody working on that ?

**Comment by sglyon** [comment]
Don't think so right now.

I wonder how much needs to be done in here, after all dependencies have been fixed.

**Comment by albop** [comment]
From a quick glance, dependencies look ready but there is a problem with
function A_mul_B! . I stopped there as you know its implementation better.

Le jeu. 9 août 2018 à 15:50, Spencer Lyon <notifications@github.com> a
écrit :

**Comment by IljaK91** [comment]
It looks like all tests pass on v0.7. Is there anything that still needs to be done here? I would be happy to help if there are some instructions about what to do.

**Comment by sglyon** [comment]
Thanks for offering to help!

This is now finished and works without errors on 0.7 and 1.0!
