### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by 121180875** [QuantEcon/BasisMatrices.jl#56]
I would like to ask for the reference of the code algorithm, thank you very much.

**Comment by cc7768** [comment]
@121180875 Not sure exactly what you're looking for -- Which code algorithm?

Lots of the algorithms originally come from "Applied computational economics and finance"

> Miranda, Mario J., and Paul L. Fackler. Applied computational economics and finance. MIT press, 2004.

**Comment by sglyon** [comment]
Yes, thanks for posting.

Most of the core basis function evaluation algorithms come from Miranda and Fackler.

Other algorithms like SplineSparse and some of the row_kron implementations were developed independently as part of this package.

**Comment by 121180875** [comment]
Thank you for your reply. I mainly want to know what literature you consulted when you wrote this package. Now I know.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chase Coleman"<notifications@github.com&gt;; 
发送时间: 2020年8月18日(星期二) 凌晨1:54
收件人: "QuantEcon/BasisMatrices.jl"<BasisMatrices.jl@noreply.github.com&gt;; 
抄送: "121180875"<121180875@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [QuantEcon/BasisMatrices.jl] reference (#56)





 
@121180875 Not sure exactly what you're looking for -- Which code algorithm?
 
Lots of the algorithms originally come from "Applied computational economics and finance"
  
Miranda, Mario J., and Paul L. Fackler. Applied computational economics and finance. MIT press, 2004.

**Comment by sglyon** [comment]
ok great. Good luck with your studies!
