### ISSUE TITLE
Error with row_kron on sparse matrices

### ISSUE THREAD

**Issue by andresdrenik** [QuantEcon/BasisMatrices.jl#62]
First, thank you so much for the amazing work you did coding the library in Julia!!!

I was looking for the equivalent of dprod in the Miranda/Fackler library and found row_kron. However, I have the following error with this code:

test1 = rand(Float64,500,2)
test2 = sprand(Float64, 500,501, 0.01)
row_kron(test1, test2)

julia> row_kron(test1, test2)
ERROR: ArgumentError: Illegal buffers for SparseMatrixCSC construction 1002 [BIG MATRIX HERE] [BIG MATRIX HERE]
Stacktrace:
 [1] SparseMatrixCSC
   @ /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SparseArrays/src/sparsematrix.jl:29 [inlined]
 [2] SparseMatrixCSC(m::Int64, n::Int64, colptr::Vector{Int64}, rowval::Vector{Int64}, nzval::Vector{Float64})
   @ SparseArrays /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/SparseArrays/src/sparsematrix.jl:44
 [3] _allocate_row_kron_out(#unused#::Type{SparseMatrixCSC}, A::Matrix{Float64}, B::SparseMatrixCSC{Float64, Int64})
   @ BasisMatrices ~/.julia/packages/BasisMatrices/PZ1uM/src/util.jl:625
 [4] _allocate_row_kron_out
   @ ~/.julia/packages/BasisMatrices/PZ1uM/src/util.jl:643 [inlined]
 [5] row_kron(A::Matrix{Float64}, B::SparseMatrixCSC{Float64, Int64})
   @ BasisMatrices ~/.julia/packages/BasisMatrices/PZ1uM/src/util.jl:33
 [6] top-level scope
   @ REPL[52]:1

However, the code works with:

row_kron(test1, Matrix(test2))

I apologize if this is something basic. I'm running this code on:

Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
Environment:
  JULIA_EDITOR = code

**Comment by jstac** [comment]
Thanks for your question @andresdrenik .  Could you please provide a full minimal example, starting with `using XYZ`?

**Comment by andresdrenik** [comment]
Hi @jstac! Here it is:

```
using SparseArrays, CompEcon

test1 = rand(Float64,500,2)
test2 = sprand(Float64, 500,501, 0.01)
row_kron(test1, test2)
```

Thank you!

**Comment by jstac** [comment]
Thanks @andresdrenik :-)

I confirm that I get the same error.  I think @sglyon is author of this code.  @sglyon , might you have time to look at this?  Many thanks in advance.

**Comment by sglyon** [comment]
Fixed! Thanks for the heas up
